name: Mirror to Gitee

on: [push, delete]

jobs:
  mirror_to_gitee:
    name: Mirror to Gitee
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Mirror to Gitee
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@gitee.com:tsund/blog.git
          ssh_private_key: ${{ secrets.GITEE_KEY }}
